name: flutter_admin_dashboard_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  adaptive_theme:
  animate_do: ^3.1.2
  collection:
  cupertino_icons:
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.9

  flutter_web_plugins:
    sdk: flutter
  gap:
  go_router:
  google_fonts:
  hooks_riverpod: ^2.4.9
  intersperse:
  recase:
  responsive_framework:
  simple_logger:
  two_dimensional_scrollables:

dev_dependencies:
  build_runner:
  build_verify:
  flutter_test:
    sdk: flutter
  go_router_builder:
  pedantic_mono:

flutter:
  uses-material-design: true
