// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3Mn2wP_Z9espVLCcThFLgfEf8QUtHKM',
    appId: '1:645483594555:web:f386cbabb7b99242992d1e',
    messagingSenderId: '645483594555',
    projectId: 'apply-fast',
    authDomain: 'apply-fast.firebaseapp.com',
    storageBucket: 'apply-fast.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtagzdr_QERvA7y8S01K3FWwqppLnO0fM',
    appId: '1:645483594555:android:7900f2c5f88102bc992d1e',
    messagingSenderId: '645483594555',
    projectId: 'apply-fast',
    storageBucket: 'apply-fast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjiOlMl3tENu3QjhzgMxObL9OWIexCa4',
    appId: '1:645483594555:ios:8da8de68bf098b90992d1e',
    messagingSenderId: '645483594555',
    projectId: 'apply-fast',
    storageBucket: 'apply-fast.appspot.com',
    iosBundleId: 'com.applyfast.jobs.philotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLjiOlMl3tENu3QjhzgMxObL9OWIexCa4',
    appId: '1:645483594555:ios:10f13cbf018195f6992d1e',
    messagingSenderId: '645483594555',
    projectId: 'apply-fast',
    storageBucket: 'apply-fast.appspot.com',
    iosBundleId: 'com.example.flutterAdminDashboardTemplate.RunnerTests',
  );
}
